# Generated by Django 5.2.1 on 2025-06-08 05:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['setting_name'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='SWG Infinity', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('starting', 'Starting')], default='offline', max_length=20)),
                ('player_count', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=1000)),
                ('uptime', models.DurationField(default=datetime.timedelta(0))),
                ('last_restart', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='CPU usage percentage')),
                ('memory_usage', models.FloatField(default=0.0, help_text='Memory usage percentage')),
                ('message_of_the_day', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Status',
                'verbose_name_plural': 'Server Statuses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_x', models.FloatField(blank=True, null=True)),
                ('location_y', models.FloatField(blank=True, null=True)),
                ('location_z', models.FloatField(blank=True, null=True)),
                ('planet', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_playtime', models.DurationField(default=datetime.timedelta(0))),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('favorite_planet', models.CharField(blank=True, max_length=50, null=True)),
                ('credits_earned', models.BigIntegerField(default=0)),
                ('experience_points', models.BigIntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('guild_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pvp_kills', models.IntegerField(default=0)),
                ('pvp_deaths', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Stats',
                'verbose_name_plural': 'Player Stats',
            },
        ),
    ]
